config/routes.rb
Intellical::Application.routes.draw do
  devise_for :users

  root :to => "guest#index"

  #admin routes
  # get "admin/" => "admin#index", :as => "admin_index"

  resources :packets do
    collection do
      get "search" => "packets#search"
    end
    member do
      get "questions" => "packets#questions_index"
      get "questions_search" => "packets#questions_search"
      post "add_question/:question_id" => "packets#add_question", :as => "add_question"
      delete "destroy_question/:question_id" => "packets#destroy_question", :as => "destroy_question"
    end
  end

  resources :questions do
    resources :choices
  end
  resources :intelligences

  resources :choices, :only =>[] do
    resources :scores
  end

  resources :runs do
    collection do
      get "input_date/:packet_id" => "runs#input_date", :as => "input_date"
    end
    member do
      put "start_run" => "runs#start_run", :as => "start"
      put "stop_run" => "runs#stop_run", :as => "stop"
    end
    resources :answers do
      collection do
        put "update_answer/:question_id" => "answers#update_answer", :as => "update_answer"
        get "statistic" => "answers#statistic", :as => "statistic"
        get "chart" => "answers#chart", :as => "chart"
      end
    end
  end

  resources :users do
    member do
      get "add_role" => "users#add_role"
      post "create_role" => "users#create_role"
      delete "destroy_role/:role_id" => "users#destroy_role", :as => "destroy_role"
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content
  has_many :choices
  has_many :packet_questions
  has_many :packets, :through => :packet_questions
  validates_uniqueness_of :content

  def self.search term
    result = Question.order(:content)
    if term
      term.downcase!
      return result.where("replace(lower(content), '\r\n', ' ') LIKE ?", "%#{term}%")
    end
    return result
  end

  def score_range
    maximum, minimum = false, false
    choices.each do |choice|
      choice.scores.each do |score|
        maximum = score.value if maximum == false || score.value > maximum
        minimum = score.value if minimum == false || score.value < minimum
      end
    end
    return false if maximum == false || minimum == false
    return "from " + minimum.to_s + " to " + maximum.to_s
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  def index
    @questions = Question.search(params[:search])
                         .paginate(:per_page => 10, :page => params[:page])
  end

  def show
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(params[:question])
    response = @question.save ? "create_success" : "create_failed"
    respond_to do |format|
      format.js { render response }      
    end
  end

  def update
    @question = Question.find(params[:id])
    response = @question.update_attributes(params[:question]) ? "update_success" : "update_failed"
    respond_to do |format|
      format.js { render response }      
    end
  end

  def destroy
    @question = Question.find(params[:id])
    response = @question.delete ? "destroy_success" : "destroy_failed"
    respond_to do |format|
      format.js { render response }      
    end
  end
end

app/views/questions/_form.html.erb
<%= form_for(question, :remote => true, :role => "form") do |f| %>
  <div class="form-group">
    <%= f.label(:content, :class=>"form-label") %>
    <%= f.text_area(:content, :class=>"form-control", :rows=>"7", :required => "true") %>
  </div>
  <div class="form-group">
    <%= f.submit("Save", :class=> "btn btn-info") %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= index + 1 %></td>
  <td><%= question.content %></td>
  <td><%= question.score_range || "?" %></td>
  <td>
    <%= link_to raw("<i class='glyphicon glyphicon-edit'></i> Edit"), edit_question_path(question) %>
    |
    <%= link_to raw("<i class='glyphicon glyphicon-trash'></i> Delete"), question_path(question), :remote => true, :confirm => "Are you sure?", :method => :delete %>
    |
    <%= link_to raw("<i class='glyphicon glyphicon-wrench'></i> Manage Choices"),  question_choices_path(question) %>
    |
    <%= link_to raw("<i class='glyphicon glyphicon-ok'></i> Preview"), question_path(question), :target => :blank %>
  </td>
</tr>

app/views/questions/_questions_table.html.erb
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <thead>
        <td width="1%">#</td>
        <td>Content</td>
        <td>Score Range</td>
        <td>Options</td>
      </thead>
    </tr>
  </thead>
  <tbody>
    <% if questions.size == 0 %>
      <%= render :partial => "shared/empty" %>
    <% else %>
      <% questions.each_with_index do |question, index| %>
        <%= render :partial => "question", locals: { :question => question, :index => index + questions.offset } %>
      <% end %>
    <% end %>
  </tbody>
</table>
<div class="pagination">
  <%= will_paginate questions, :renderer => BootstrapLinkRenderer %>
</div>

app/views/questions/_search.html.erb
<form class="form-inline" form="tag" action="<%= questions_path  %>">
  <div class="input-group">
    <input type="text" class="form-control" value="<%= params[:search] %>" name="search" style="width:100%">
    <span class="input-group-addon">
      <i class="glyphicon glyphicon-search"></i>
    </span>
  </div>
</form>
<br>  

app/views/questions/create_failed.js.erb
alert("Something gonna wrong, question cannot be created!");

app/views/questions/create_success.js.erb
alert("Question successfully created!");
location.href = "<%= questions_path %>";

app/views/questions/destroy_failed.js.erb
alert("Something gonna wrong, question cannot be removed!");

app/views/questions/destroy_success.js.erb
alert("Question successfully removed!");
location.reload();

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<hr>
<div class="col-md-6">
  <%= render :partial => "form", :locals => { :question => @question } %>
</div>

app/views/questions/index.html.erb
<h1>Question List</h1>
<br>
<%= link_to raw("<i class='glyphicon glyphicon-plus'></i> Add new question"), new_question_path, :class => "btn btn-success" %>
<hr>
<%= render "search" %>
<div class="table-responsive">
  <%= render :partial => "questions_table", locals: { :questions => @questions } %>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>
<hr>
<div class="col-md-6">
  <%= render :partial => "form", :locals => { :question => @question } %>
</div>

app/views/questions/show.html.erb
<h1>Question Preview</h1>
<blockquote>
  <i><%= @question.content %></i>
</blockquote>
<hr>
<% if @question.choices.length == 0 %>
  <i>This question has no choice.</i>
<% else %>
  <h3>Choices :</h3>
<% end %>
<% @question.choices.each_with_index do |choice, index| %>
  <div style="font-size:18px">
    <%= (index + 65).chr %>. <%= choice.content %>
    <% if choice.scores.length == 0 %>
      <div style="font-size:12px">
        <i>This choice has no score.</i>
      </div>
    <% end %>
    <ul style="font-size:12px">
      <% choice.scores.each do |score| %>
        <li><%= score.intelligence.name + " : " + (score.value > 0 ? "+" : "") + score.value.to_s %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/questions/update_failed.js.erb
alert("Error, question cannot be updated!");

app/views/questions/update_success.js.erb
alert("Question successfully updated!");
location.href = "<%= questions_path %>";