config/routes.rb
Intellical::Application.routes.draw do
  devise_for :users

  root :to => "guest#index"

  #admin routes
  # get "admin/" => "admin#index", :as => "admin_index"

  resources :packets do
    collection do
      get "search" => "packets#search"
    end
    member do
      get "questions" => "packets#questions_index"
      get "questions_search" => "packets#questions_search"
      post "add_question/:question_id" => "packets#add_question", :as => "add_question"
      delete "destroy_question/:question_id" => "packets#destroy_question", :as => "destroy_question"
    end
  end

  resources :questions do
    resources :choices
  end
  resources :intelligences

  resources :choices, :only =>[] do
    resources :scores
  end

  resources :runs do
    collection do
      get "input_date/:packet_id" => "runs#input_date", :as => "input_date"
    end
    member do
      put "start_run" => "runs#start_run", :as => "start"
      put "stop_run" => "runs#stop_run", :as => "stop"
    end
    resources :answers do
      collection do
        put "update_answer/:question_id" => "answers#update_answer", :as => "update_answer"
        get "statistic" => "answers#statistic", :as => "statistic"
        get "chart" => "answers#chart", :as => "chart"
      end
    end
  end

  resources :users do
    member do
      get "add_role" => "users#add_role"
      post "create_role" => "users#create_role"
      delete "destroy_role/:role_id" => "users#destroy_role", :as => "destroy_role"
    end
  end
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
  has_many :scores
  attr_accessible :content, :question_id
  validates_presence_of :content
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  load_and_authorize_resource
  def index
    @question = Question.find(params[:question_id])
    @choices = @question.choices.order(:content)
    @choice = Choice.new
  end

  def create
    @question = Question.find(params[:question_id])
    @choice = Choice.new(params[:choice])
    @choice.question_id = @question.id
    response = @choice.save ? "create_success" : "create_failed"

    respond_to do |format|
      format.js { render response }
    end
  end

  def update
    @question = Question.find(params[:question_id])
    @choice = Choice.find(params[:id])
    response = @choice.update_attributes(params[:choice]) ? "update_success" : "update_failed"
    @choices = @question.choices.sort

    respond_to do |format|
      format.js { render response }
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @choice = Choice.find(params[:id])
    response = @choice.delete ? "destroy_success" : "destroy_failed"

    respond_to do |format|
      format.js { render response }
    end
  end
end

app/views/choices/create_failed.js.erb
alert("Choice cannot be added.");

app/views/choices/create_success.js.erb
choices = <%=raw @question.choices.to_json %>
createChoices();
$("#create_choice_form").hide();

app/views/choices/destroy_failed.js.erb
alert("Choice cannot be removed.");

app/views/choices/destroy_success.js.erb
choices = <%=raw @question.choices.to_json %>
createChoices();
$("#create_choice_form").hide();

app/views/choices/index.html.erb
<h1>Manage Choices</h1>
<hr>
<blockquote>
<i><%= @question.content %></i>
</blockquote>
<div id="choices"></div>

<form action="<%= question_choices_path(@question) %>" method="post" class="form-inline" id="create_choice_form" style="display:none;">
  <input type="text" class="form-control" name="choice[content]" style="width:20%">
  <input type="submit" value="add choice" class="btn btn-info" style="width:100px">
</form>

<form class="form-inline" method="put" id="update_choice_form" style="display:none;">
  <input type="text" class="form-control" name="choice[content]" style="width:20%">
  <input type="submit" value="save" class="btn btn-info" style="width:100px">
  <input type="button" value="cancel" class="btn btn-danger" style="width:100px" id="btn_cancel_edit_choice">
</form>

<hr>
<div id="scores_editor"><i>Click edit scores to view the of spesific choice scores</i></div>

<script type="text/javascript">
  choices = <%=raw @choices.to_json %>
  questionChoicePath = '<%= question_choice_path(@question, '') %>'
  choiceScorePath = '<%= choice_score_path('', '') %>'
  choiceScoresPath = '<%= choice_scores_path('') %>'
</script>

app/views/choices/update_failed.js.erb
alert("Choice cannot be added.");

app/views/choices/update_success.js.erb
choices = <%=raw @choices.to_json %>
createChoices();
$("#update_choice_form").hide();