config/routes.rb
Intellical::Application.routes.draw do
  devise_for :users

  root :to => "guest#index"

  #admin routes
  # get "admin/" => "admin#index", :as => "admin_index"

  resources :packets do
    collection do
      get "search" => "packets#search"
    end
    member do
      get "questions" => "packets#questions_index"
      get "questions_search" => "packets#questions_search"
      post "add_question/:question_id" => "packets#add_question", :as => "add_question"
      delete "destroy_question/:question_id" => "packets#destroy_question", :as => "destroy_question"
    end
  end

  resources :questions do
    resources :choices
  end
  resources :intelligences

  resources :choices, :only =>[] do
    resources :scores
  end

  resources :runs do
    collection do
      get "input_date/:packet_id" => "runs#input_date", :as => "input_date"
    end
    member do
      put "start_run" => "runs#start_run", :as => "start"
      put "stop_run" => "runs#stop_run", :as => "stop"
    end
    resources :answers do
      collection do
        put "update_answer/:question_id" => "answers#update_answer", :as => "update_answer"
        get "statistic" => "answers#statistic", :as => "statistic"
        get "chart" => "answers#chart", :as => "chart"
      end
    end
  end

  resources :users do
    member do
      get "add_role" => "users#add_role"
      post "create_role" => "users#create_role"
      delete "destroy_role/:role_id" => "users#destroy_role", :as => "destroy_role"
    end
  end
end

app/views/shared/_empty.html.erb
<tr>
  <td class='colspaned'>
    <center>
      <i>Empty</i>
    </center>
  </td>
</tr>

app/views/shared/_flash.html.erb
<div id="flash">
  <% if notice %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_left_menu.html.erb
<ul class="nav navbar-nav">
  <li>
    <% if can?(:read, Run) or can?(:manage, Packet) %>
      <%= link_to "Runs", runs_path %>
    <% end %>
  </li>

  <!-- Registrations -->
  <% if can?(:manage, Intelligence) and can?(:manage, User) %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Registrations <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "Intelligences", intelligences_path %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
      </ul>
    </li>
  <% end %>

  <!-- Questions -->
  <% if can?(:manage, Packet) or can?(:manage, Question) %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Questions Management <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <% if can?(:manage, Packet) %>
          <li> 
            <%= link_to "Question packets", packets_path %> 
          </li>
        <% end %>
        <% if can?(:manage, Question) %>
          <li>
            <%= link_to "Question list", questions_path %> 
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>

</ul>

app/views/shared/_menu.html.erb
<div class="navbar-collapse collapse">
  <% if user_signed_in? %>
    <%= render :partial => "shared/left_menu" %>
  <% end %>

  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <p class="navbar-text pull-right">Welcome <%= current_user.email %>, <%= link_to "sign out", destroy_user_session_path, :method => :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign in", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Show/Hide Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Intellical", root_path, :class => "navbar-brand" %>
    </div>

    <%= render :partial => "shared/menu" %>
  </div>
</div>