config/routes.rb
Intellical::Application.routes.draw do
  devise_for :users

  root :to => "guest#index"

  #admin routes
  # get "admin/" => "admin#index", :as => "admin_index"

  resources :packets do
    collection do
      get "search" => "packets#search"
    end
    member do
      get "questions" => "packets#questions_index"
      get "questions_search" => "packets#questions_search"
      post "add_question/:question_id" => "packets#add_question", :as => "add_question"
      delete "destroy_question/:question_id" => "packets#destroy_question", :as => "destroy_question"
    end
  end

  resources :questions do
    resources :choices
  end
  resources :intelligences

  resources :choices, :only =>[] do
    resources :scores
  end

  resources :runs do
    collection do
      get "input_date/:packet_id" => "runs#input_date", :as => "input_date"
    end
    member do
      put "start_run" => "runs#start_run", :as => "start"
      put "stop_run" => "runs#stop_run", :as => "stop"
    end
    resources :answers do
      collection do
        put "update_answer/:question_id" => "answers#update_answer", :as => "update_answer"
        get "statistic" => "answers#statistic", :as => "statistic"
        get "chart" => "answers#chart", :as => "chart"
      end
    end
  end

  resources :users do
    member do
      get "add_role" => "users#add_role"
      post "create_role" => "users#create_role"
      delete "destroy_role/:role_id" => "users#destroy_role", :as => "destroy_role"
    end
  end
end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :packet
  attr_accessible :finish_datetime, :start_datetime, :packet_id, :running

  validates_presence_of :start_datetime
  validates_presence_of :finish_datetime
  validates_presence_of :packet_id

  has_many :answers

  def is_running?
    running
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  load_and_authorize_resource
  def index
    if can? :manage, Run
      @runs = Run.order("start_datetime desc").all
    else
      @runs = Run.order("start_datetime desc").where(:running => true)
    end
  end

  def new
    @run = Run.new
  end

  def create
    @run = Run.new(params[:run])
    # puts ">>>>>" + @run.inspect
    response = @run.save ? "create_success" : "create_failed"
    respond_to do |format|
      format.js { render response }
    end
  end

  def destroy
    @run = Run.find(params[:id])
    response = @run.delete ? "destroy_success" : "destroy_failed"
    respond_to do |format|
      format.js { render response }
    end
  end

  def input_date
    @packet = Packet.find(params[:packet_id])
    @run = Run.new
    @run.packet_id = @packet.id
    respond_to do |format|
      format.js
    end
  end

  def start_run
    @run = Run.find(params[:id])
    @run.running = true
    response = @run.save ? "start_run_success" : "start_run_failed"
    respond_to do |format|
      format.js { render response }
    end
  end

  def stop_run
    @run = Run.find(params[:id])
    @run.running = false
    response = @run.save ? "stop_run_success" : "stop_run_failed"
    respond_to do |format|
      format.js { render response }
    end
  end
end

app/views/runs/_create_success.html.erb
<div class="alert alert-success">
  <strong>Congratulations!</strong>, run successfully created, <%= link_to raw("see run list"), runs_path %>
</div>

app/views/runs/_input_date.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><b>Input Run Dates</b></div>
  <div class="panel-body" id="input_run_dates_container">
    <%= render :partial => "form", :locals => { run: run } %>
  </div>
</div>

app/views/runs/_start_run_control.html.erb
<%= link_to raw("<i class='glyphicon glyphicon-play'></i> run"), start_run_path(run), :remote => true, :method => :put, :class => 'start-run-control', :disable_with => "starting run..." %>

app/views/runs/_stop_run_control.html.erb
<%= link_to raw("<i class='glyphicon glyphicon-stop'></i> cancel run"), stop_run_path(run), :remote => true, :method => :put, :class => 'cancel-run-control', :confirm => "Are you sure to stop current run?", :disable_with => "terminating current run..." %>     

app/views/runs/create_failed.js.erb
alert("Something's wrong, run cannot be created.");

app/views/runs/destroy_failed.js.erb
alert("Error, run cannot be removed from entries");
location.reload();

app/views/runs/destroy_success.js.erb
alert("Run successfully removed from entries");
location.reload();

app/views/runs/index.html.erb
<h1>Run List</h1>
<% if can?(:create, Run) or can?(:manage, Packet) %>
  <%= link_to raw("<i class='glyphicon glyphicon-plus'></i> Create new run"), new_run_path, :class => "btn btn-info" %>
<% end %>
<hr>

<% if @runs.length == 0 %>
  <i>No runs added. </i><%= link_to "add run now", new_run_path if can? :manage, :runs %>
<% end %>

<% @runs.each_with_index do |run, index| %>
  <%= render :partial => "run", :locals => { run: run, index: index } %>
<% end %>

app/views/runs/input_date.js.erb
$("#new_run_container").html("<%=j render :partial=>'input_date', :locals => { packet: @packet, run: @run } %>");

app/views/runs/new.html.erb
<h1>Create new run</h1>
<hr>
<div id="new_run_container">
  <div class="panel panel-default">
    <div class="panel-heading"><b>Select Questions Packet</b></div>
    <div class="panel-body" id="">
      <div class="input-group" style="width: 100%">
        <input type="text" class="form-control" id="search_packets" data-target="<%= search_packets_path %>">
        <span class="input-group-addon" style="width:5%">
          <i class="glyphicon glyphicon-search"></i>
        </span>
      </div>
      <br>
      <div id="packet_list">
        <center>
          <i>select questions packet by searching some packets to create new run.</i>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/runs/start_run_failed.js.erb
alert("Run cannot be started.")

app/views/runs/start_run_success.js.erb
$("#run_<%= @run.id %>").addClass("active-run").find(".run_status_control").html("<%=j render :partial => 'stop_run_control', :locals=> { run: @run } %>");

app/views/runs/stop_run_failed.js.erb
alert("Run cannot be stopped.")

app/views/runs/stop_run_success.js.erb
$("#run_<%= @run.id %>").removeClass("active-run").find(".run_status_control").html("<%=j render :partial => 'start_run_control', :locals=> { run: @run } %>");